### ISSUE TITLE
Address is already backed

### ISSUE THREAD

**Issue by findo** [ucsb-seclab/hal-fuzz#1]
I use the dump_symbols.py to dump symbols of an axf file, which is ELF. It failed: 

```
Traceback (most recent call last):
  File "dump_symbols.py", line 10, in <module>
    p = angr.Project(fname)
  File "/home/wangfeng/.local/lib/python3.8/site-packages/angr/project.py", line 224, in __init__
    self.simos.configure_project()
  File "/home/wangfeng/.local/lib/python3.8/site-packages/angr/simos/linux.py", line 45, in configure_project
    self._loader_addr = self.project.loader.extern_object.allocate()
  File "/home/wangfeng/.local/lib/python3.8/site-packages/cle/loader.py", line 223, in extern_object
    self._internal_load(self._extern_object)
  File "/home/wangfeng/.local/lib/python3.8/site-packages/cle/loader.py", line 774, in _internal_load
    self._map_object(obj)
  File "/home/wangfeng/.local/lib/python3.8/site-packages/cle/loader.py", line 876, in _map_object
    self.memory.add_backer(base_addr, obj.memory)
  File "/home/wangfeng/.local/lib/python3.8/site-packages/cle/memory.py", line 194, in add_backer
    raise ValueError("Address %#x is already backed!" % start)
ValueError: Address 0x8100000 is already backed!
```
How to solve this ?

**Comment by subwire** [comment]
This looks like an angr or cle bug, as this occurs during the initial loading of the binary.
I'll follow up on your other issue on angr/angr.

**Comment by findo** [comment]
Angr team solved it! When I run the same script again, it generates the YAML file but gives some ERRORs:
```
WARNING | 2020-10-21 17:45:43,421 | cle.backends.elf.elf | ELF file /home/wangfeng/hal-fuzz/jiuyuan/test.elf is loading a segment with an inappropriate alignment. It might not work in all contexts.
WARNING | 2020-10-21 17:45:43,463 | angr.analyses.cfg.cfg_fast | "auto_load_libs" is enabled. With libraries loaded in project, CFGFast will cover libraries, which may take significantly more time than expected. You may reload the binary with "auto_load_libs" disabled, or specify "regions" to limit the scope of CFG recovery.
Deprecation warning: Use self.model.get_any_node() instead of get_any_node
ERROR   | 2020-10-21 17:45:44,121 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0x80004c2 of function 0x80004c2.
ERROR   | 2020-10-21 17:45:44,122 | angr.analyses.cfg.cfg_fast | Decoding error occurred at address 0x80013ee of function 0x80013ee.
WARNING | 2020-10-21 17:45:44,150 | angr.storage.memory_mixins.default_filler_mixin | The program is accessing memory or registers with an unspecified value. This could indicate unwanted behavior.
WARNING | 2020-10-21 17:45:44,150 | angr.storage.memory_mixins.default_filler_mixin | angr will cope with this by generating an unconstrained symbolic variable and continuing. You can resolve this by:
WARNING | 2020-10-21 17:45:44,150 | angr.storage.memory_mixins.default_filler_mixin | 1) setting a value to the initial state
WARNING | 2020-10-21 17:45:44,150 | angr.storage.memory_mixins.default_filler_mixin | 2) adding the state option ZERO_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to make unknown regions hold null
WARNING | 2020-10-21 17:45:44,150 | angr.storage.memory_mixins.default_filler_mixin | 3) adding the state option SYMBOL_FILL_UNCONSTRAINED_{MEMORY,REGISTERS}, to suppress these messages.
WARNING | 2020-10-21 17:45:44,150 | angr.storage.memory_mixins.default_filler_mixin | Filling register r1 with 4 unconstraarchitecture: ARMEL
base_address: 134217728
entry_point: 134218033
symbols:
  134218033: _main_stk
  134218037: _main_scatterload
  134218041: _main_init
  134218053: Reset_Handler
  134218079: WWDG_IRQHandler
  134218089: _ll_ushift_r
  134218121: __aeabi_memset8
  134218135: __aeabi_memclr8
  134218139: _memset$wrapper
  134218157: __aeabi_i2d
  134218191: __aeabi_d2uiz
  134218241: __aeabi_cdrcmple
  134218289: _double_round
  134218319: _double_epilogue
  134218477: __scatterload_rt2
  134218513: _ll_shift_l
  134218543: __decompress1
  134218629: APP_Init
  134218679: BusFault_Handler
  134218681: DMA1_Channel2_IRQHandler
  134218693: DMA1_Channel3_IRQHandler
  134218705: DMA1_Channel4_IRQHandler
  134218717: DMA1_Channel5_IRQHandler
  134218729: DMA1_Channel6_IRQHandler
  134218741: DMA1_Channel7_IRQHandler
  134218753: DMA_SetConfig
  134218795: DebugMon_Handler
  134218797: Error_Handler
  134218801: Get_2s_Frame
  134218877: HAL_DMA_Abort
  134218949: HAL_DMA_Abort_IT
  134219253: HAL_DMA_IRQHandler
"out.yaml" 151L, 4707C                                                                                  1,1           Top
ined bytes referenced from 0x800081d ($d+0x1 in test.elf (0x800081d))
WARNING | 2020-10-21 17:45:44,151 | angr.storage.memory_mixins.default_filler_mixin | Filling register r0 with 4 unconstrained bytes referenced from 0x800081d ($d+0x1 in test.elf (0x800081d))
WARNING | 2020-10-21 17:45:44,153 | angr.storage.memory_mixins.default_filler_mixin | Filling register r2 with 4 unconstrained bytes referenced from 0x800081d ($d+0x1 in test.elf (0x800081d))
WARNING | 2020-10-21 17:45:44,155 | angr.storage.memory_mixins.default_filler_mixin | Filling register r3 with 4 unconstrained bytes referenced from 0x800081d ($d+0x1 in test.elf (0x800081d))
WARNING | 2020-10-21 17:45:44,155 | angr.storage.memory_mixins.default_filler_mixin | Filling register r4 with 4 unconstrained bytes referenced from 0x800081d ($d+0x1 in test.elf (0x800081d))
WARNING | 2020-10-21 17:45:44,158 | angr.storage.memory_mixins.default_filler_mixin | Filling register r6 with 4 unconstrained bytes referenced from 0x800081d ($d+0x1 in test.elf (0x800081d))
WARNING | 2020-10-21 17:45:44,169 | angr.storage.memory_mixins.default_filler_mixin | Filling register r5 with 4 unconstrained bytes referenced from 0x800081d ($d+0x1 in test.elf (0x800081d))
WARNING | 2020-10-21 17:45:44,184 | angr.storage.memory_mixins.default_filler_mixin | Filling register lr with 4 unconstrained bytes referenced from 0x800083d (HAL_DMA_Init+0x0 in test.elf (0x800083d))
WARNING | 2020-10-21 17:45:44,197 | angr.storage.memory_mixins.default_filler_mixin | Filling register r0 with 4 unconstrained bytes referenced from 0x8001387 ($d+0x1 in test.elf (0x8001387))
WARNING | 2020-10-21 17:45:44,203 | angr.storage.memory_mixins.default_filler_mixin | Filling register r4 with 4 unconstrained bytes referenced from 0x800138d (HAL_UART_Init+0x0 in test.elf (0x800138d))
WARNING | 2020-10-21 17:45:44,203 | angr.storage.memory_mixins.default_filler_mixin | Filling register r5 with 4 unconstrained bytes referenced from 0x800138d (HAL_UART_Init+0x0 in test.elf (0x800138d))
WARNING | 2020-10-21 17:45:44,204 | angr.storage.memory_mixins.default_filler_mixin | Filling register r6 with 4 unconstrained bytes referenced from 0x800138d (HAL_UART_Init+0x0 in test.elf (0x800138d))
WARNING | 2020-10-21 17:45:44,204 | angr.storage.memory_mixins.default_filler_mixin | Filling register lr with 4 unconstrained bytes referenced from 0x800138d (HAL_UART_Init+0x0 in test.elf (0x800138d))
ERROR   | 2020-10-21 17:45:45,363 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported Unop Iop_Clz32.
ERROR   | 2020-10-21 17:45:45,364 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | Unsupported Unop Iop_Clz32.
ERROR   | 2020-10-21 17:45:45,373 | angr.analyses.xrefs.SimEngineXRefsVEX | Unsupported Unop Iop_Clz32.
ERROR   | 2020-10-21 17:45:45,374 | angr.analyses.xrefs.SimEngineXRefsVEX | Unsupported Unop Iop_Clz32.
WARNING | 2020-10-21 17:45:45,579 | angr.analyses.propagator.engine_vex.SimEnginePropagatorVEX | integer division or modulo by zero
```
Does the last four ERRORs affect the final fuzzing result ?

**Comment by subwire** [comment]
Nope. That all comes from CFG generation, which we only did to help prune some weird edge-cases where names were being associated with things that weren't functions due to poor-quality ELF files from embedded tooling.  
angr is notoriously verbose, and you'll come to ignore most of its output.
The things that *do* affect your fuzzing come next, namely the configuration of your target, seed inputs, and handler implementations.
